repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [ jupyter ]
      - id: end-of-file-fixer
        exclude_types: [ jupyter ]
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.11
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [
          --python-version=3.12,
          --disallow-untyped-calls,
          --disallow-untyped-defs,
          --disallow-incomplete-defs,
          --check-untyped-defs,
          --no-implicit-optional,
          --warn-redundant-casts,
          --ignore-missing-imports,
        ]
        exclude_types: [ jupyter ]
        exclude: ^tests/
        additional_dependencies:
          - types-PyYAML
          - types-requests
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.6'
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
