[tool.poetry]
name = "pl8catch"
version = "0.0.1"
description = "Solution to automatically recognize license plates."
authors = ["Daniel Sousa"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.1"
opencv-python = "^4.9.0.80"
pytesseract = "^0.3.10"
ultralytics = "^8.2.13"
streamlit = "^1.34.0"
fastapi = "^0.111.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.4.0"
pytest = "^7.4.2"
mypy = "^1.5.1"
ruff = "^0.0.287"
black = "^23.9.1"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true

[tool.black]
line-length = 120

[tool.bandit.assert_used]
skips = ['*_test.py', '*/test_*.py']
