apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pl8catch.fullname" . }}-config
  labels:
    {{- include "pl8catch.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- toYaml .Values.app.config | nindent 4 }}
