license_plate_ocr:
  resizing_threshold: 15000
  pytesseract_config: "--psm 8"
  confidence_threshold: 0.1

models:
  object_detection: "/app/models/yolo12s.pt"
  license_plate: "/app/models/license_plate_model.pt"
